on:
  push:
    branches:
      - develop  # adjust if you deploy from a different branch
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # use your desired Node.js version
 
      - name: Install dependencies
        run: npm install
 
      - name: Build the project
        run: npm run build
 
      # Copy the built files and server code to the VM using scp.
      - name: Copy files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}  # optional if using default port 22, can be omitted
          source: "."
          target: "/home/${{ secrets.VM_USERNAME }}/form-app"  # adjust target path as needed
 
      # Execute remote commands via SSH to install dependencies and restart the app.
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd ~/form-app
            npm install --production
            # If using PM2, restart the app or start if not running:
            pm2 restart app || pm2 start server.js --name app